********************************************************************************
* SPICE netlist generated by HiPer Verify's NetList Extractor
*
* Extract Date/Time:	Thu Feb 14 18:19:36 2013
* L-Edit Version:		L-Edit Win64 16.00.20130213.07:27:00
*
* Rule Set Name:		
* TDB File Name:		S:\TannerTools\main\TannerToolsShippingFiles\Process\Generic_250nm\Generic_250nm_AnalogLib\OA\lib.defs
* Command File:		S:\TannerTools\main\TannerToolsShippingFiles\Process\Generic_250nm\Generic_250nm_Tech\OA\Rules\Generic_250nm_LVS.cal
* Cell Name:			BiasGen
* Write Flat:			NO
********************************************************************************

.LIB '..\..\..\Generic_250nm_Tech\Generic_250nm.lib' LVS

****************************************
.SUBCKT CurrentMirror_PMOS25_Auto1 M1/G M2/D S
M1 M2/D M1/G S S PMOS25 l=5e-007 w=1.5e-006 ad=5.625e-013 as=1.125e-012 pd=2.25e-006 ps=4.5e-006  $ (0.75 0 1.25 1.5)
M2 S M1/G M2/D S PMOS25 l=5e-007 w=1.5e-006 ad=5.625e-013 as=5.625e-013 pd=2.25e-006 ps=2.25e-006  $ (2 0 2.5 1.5)
M3 M1/G M1/G S S PMOS25 l=5e-007 w=1.5e-006 ad=5.625e-013 as=5.625e-013 pd=2.25e-006 ps=2.25e-006  $ (3.25 0 3.75 1.5)
M4 S M1/G M1/G S PMOS25 l=5e-007 w=1.5e-006 ad=5.625e-013 as=5.625e-013 pd=2.25e-006 ps=2.25e-006  $ (4.5 0 5 1.5)
M5 M1/G M1/G S S PMOS25 l=5e-007 w=1.5e-006 ad=5.625e-013 as=5.625e-013 pd=2.25e-006 ps=2.25e-006  $ (5.75 0 6.25 1.5)
M6 S M1/G M1/G S PMOS25 l=5e-007 w=1.5e-006 ad=5.625e-013 as=5.625e-013 pd=2.25e-006 ps=2.25e-006  $ (7 0 7.5 1.5)
M7 M2/D M1/G S S PMOS25 l=5e-007 w=1.5e-006 ad=5.625e-013 as=5.625e-013 pd=2.25e-006 ps=2.25e-006  $ (8.25 0 8.75 1.5)
M8 S M1/G M2/D S PMOS25 l=5e-007 w=1.5e-006 ad=1.125e-012 as=5.625e-013 pd=4.5e-006 ps=2.25e-006  $ (9.5 0 10 1.5)
* Device count
* M(PMOS25)		8
* Number of devices:	8
* Number of nodes:	3
.ENDS

****************************************
.SUBCKT Capacitor_MiM_Auto1 Bottom Top
X1 Top Bottom Capacitor_MiM l=1e-005 w=1e-005  $ (0 0 10 10)
* Device count
* X(Capacitor_MiM)		1
* Number of devices:	1
* Number of nodes:	2
.ENDS

****************************************
.SUBCKT nmos25_Auto1 1 D G S
M1 D G S 1 NMOS25 l=5e-007 w=3e-006 ad=1.125e-012 as=1.95e-012 pd=3.75e-006 ps=7.3e-006  $ (0 0 0.5 3)
M2 S G D 1 NMOS25 l=5e-007 w=3e-006 ad=1.95e-012 as=1.125e-012 pd=7.3e-006 ps=3.75e-006  $ (1.25 0 1.75 3)
* Device count
* M(NMOS25)		2
* Number of devices:	2
* Number of nodes:	4
.ENDS

****************************************
.SUBCKT rnp_Auto1 Neg Pos
X1 1 Neg rnp l=4e-006 w=2e-006  $ (0 0 2 4)
X2 1 2 rnp l=4e-006 w=2e-006  $ (3 0 5 4)
X3 Pos 2 rnp l=4e-006 w=2e-006  $ (6 0 8 4)
* Device count
* X(rnp)		3
* Number of devices:	3
* Number of nodes:	4
.ENDS

****************************************
.SUBCKT DiffPair_NMOS25_Auto1 1 2 3 4 5 M1/D M1/G M2/D M2/G S
M1 S 1 2 3 NMOS25 l=5e-007 w=3e-006 ad=1.125e-012 as=2.25e-012 pd=3.75e-006 ps=7.5e-006  $ (0.75 0 1.25 3)
M2 M1/D M1/G S 3 NMOS25 l=5e-007 w=3e-006 ad=1.125e-012 as=1.125e-012 pd=3.75e-006 ps=3.75e-006  $ (2 0 2.5 3)
M3 S M1/G M1/D 3 NMOS25 l=5e-007 w=3e-006 ad=1.125e-012 as=1.125e-012 pd=3.75e-006 ps=3.75e-006  $ (3.25 0 3.75 3)
M4 M2/D M2/G S 3 NMOS25 l=5e-007 w=3e-006 ad=1.125e-012 as=1.125e-012 pd=3.75e-006 ps=3.75e-006  $ (4.5 0 5 3)
M5 S M2/G M2/D 3 NMOS25 l=5e-007 w=3e-006 ad=1.125e-012 as=1.125e-012 pd=3.75e-006 ps=3.75e-006  $ (5.75 0 6.25 3)
M6 4 5 S 3 NMOS25 l=5e-007 w=3e-006 ad=2.25e-012 as=1.125e-012 pd=7.5e-006 ps=3.75e-006  $ (7 0 7.5 3)
* Device count
* M(NMOS25)		6
* Number of devices:	6
* Number of nodes:	10
.ENDS

****************************************

XU20 bp bn Vdd CurrentMirror_PMOS25_Auto1  $ (13.5 19.125 25.75 24.225) $T=14.25 21.275 0 0 1
XXC1 bn Vdd Capacitor_MiM_Auto1  $ (-0.195 11.08 13.405 24.18) $T=11.355 12.63 1 180 -1
XXM1n Vss bn bn Vss nmos25_Auto1  $ (13.4 14.025 16.95 19.175) $T=16.05 17.675 0 180 1
XXR1 Vss N1 rnp_Auto1  $ (16.95 12.425 25.45 18.525) $T=17.2 17.475 1 0 -1
XU22 Vss N1 Vss N1 Vss bp bn bp bn N1 DiffPair_NMOS25_Auto1  $ (25.75 12.425 33.35 22.575) $T=31.05 13.375 0 270 1
* Top level device count
* Number of devices:	0
* Number of nodes:	5


* Cumulative top level and subcircuit device count
* M(NMOS25)		8
* M(PMOS25)		8
* X(Capacitor_MiM)		1
* X(rnp)		3
* Number of devices:	20
* Number of nodes:	28
