********************************************************************************
* SPICE netlist generated by HiPer Verify's NetList Extractor
*
* Extract Date/Time:	Thu Feb 14 12:36:47 2013
* L-Edit Version:		L-Edit Win64 16.00.20130213.07:27:00
*
* Rule Set Name:		
* TDB File Name:		S:\TannerTools\main\TannerToolsShippingFiles\Process\Generic_250nm\Generic_250nm_AnalogLib\OA\lib.defs
* Command File:		S:\TannerTools\main\TannerToolsShippingFiles\Process\Generic_250nm\Generic_250nm_Tech\OA\Rules\Generic_250nm_LVS.cal
* Cell Name:			DAC_BIT
* Write Flat:			NO
********************************************************************************

.LIB '..\..\..\Generic_250nm_Tech\Generic_250nm.lib' LVS

****************************************
.SUBCKT pmos25_Auto1 1 2 B D S
M1 D 1 S B PMOS25 l=2.5e-007 w=5.1e-006 ad=1.9125e-012 as=3.315e-012 pd=5.85e-006 ps=1.15e-005  $ (0 0 0.25 5.1)
M2 2 1 D B PMOS25 l=2.5e-007 w=5.1e-006 ad=1.9125e-012 as=1.9125e-012 pd=5.85e-006 ps=5.85e-006  $ (1 0 1.25 5.1)
* Device count
* M(PMOS25)		2
* Number of devices:	2
* Number of nodes:	5
.ENDS

****************************************
.SUBCKT nmos25_Auto1 1 2 B D S
M1 D 1 S B NMOS25 l=2.5e-007 w=1.9e-006 ad=7.125e-013 as=1.235e-012 pd=2.65e-006 ps=5.1e-006  $ (0 0 0.25 1.9)
M2 2 1 D B NMOS25 l=2.5e-007 w=1.9e-006 ad=7.125e-013 as=7.125e-013 pd=2.65e-006 ps=2.65e-006  $ (1 0 1.25 1.9)
* Device count
* M(NMOS25)		2
* Number of devices:	2
* Number of nodes:	5
.ENDS

****************************************
.SUBCKT HD_rhp_Auto1 RM RP
X1 RM RP rhp l=1e-005 w=2e-006  $ (0 0 2 10)
* Device count
* X(rhp)		1
* Number of devices:	1
* Number of nodes:	2
.ENDS

****************************************
.SUBCKT HD_rhp_Auto1[6x1]x[2500x12150] 1 2 3 4 5 6 7 8 9 10 RM RP
X2 RM RP HD_rhp_Auto1  $ (-0.25 -1.075 2.25 11.075) $T=0 0 0 0 1
X3 1 2 HD_rhp_Auto1  $ (2.25 -1.075 4.75 11.075) $T=2.5 0 0 0 1
X4 3 4 HD_rhp_Auto1  $ (4.75 -1.075 7.25 11.075) $T=5 0 0 0 1
X5 5 6 HD_rhp_Auto1  $ (7.25 -1.075 9.75 11.075) $T=7.5 0 0 0 1
X6 7 8 HD_rhp_Auto1  $ (9.75 -1.075 12.25 11.075) $T=10 0 0 0 1
X7 9 10 HD_rhp_Auto1  $ (12.25 -1.075 14.75 11.075) $T=12.5 0 0 0 1
* Device count
* Number of devices:	0
* Number of nodes:	12
.ENDS

****************************************

M1 VrefM bb b VrefM NMOS25 l=2.5e-007 w=1.9e-006 ad=7.125e-013 as=7.125e-013 pd=2.65e-006 ps=2.65e-006  $ (20.725 32.775 22.625 33.025)
M2 bb Bit_In VrefM VrefM NMOS25 l=2.5e-007 w=1.9e-006 ad=1.235e-012 as=7.125e-013 pd=5.1e-006 ps=2.65e-006  $ (20.725 33.775 22.625 34.025)
M3 VrefP bb b VrefP PMOS25 l=2.5e-007 w=5.1e-006 ad=1.9125e-012 as=1.9125e-012 pd=5.85e-006 ps=5.85e-006  $ (12.775 32.775 17.875 33.025)
M4 bb Bit_In VrefP VrefP PMOS25 l=2.5e-007 w=5.1e-006 ad=3.315e-012 as=1.9125e-012 pd=1.15e-005 ps=5.85e-006  $ (12.775 33.775 17.875 34.025)
XU5 bb b VrefP VrefP b pmos25_Auto1  $ (10.975 28.325 18.625 34.425) $T=17.875 30.775 0 270 1
XU3 bb b VrefM VrefM b nmos25_Auto1  $ (20.425 28.825 23.925 33.925) $T=22.625 30.775 0 270 1
XU10 1 Vin RM 2 3 2 1 Vout 3 Vout RM b HD_rhp_Auto1[6x1]x[2500x12150]  $ (9.95 12.725 24.95 24.875) $T=10.2 13.8 0 0 1
* Top level device count
* M(NMOS25)		2
* M(PMOS25)		2
* Number of devices:	4
* Number of nodes:	11


* Cumulative top level and subcircuit device count
* M(NMOS25)		4
* M(PMOS25)		4
* X(rhp)		1
* Number of devices:	9
* Number of nodes:	35
