; Technology File Generic 0.25u
;
;********************************
; CONTROLS
;********************************
controls(
   techParams(
      (gridResolution   0.05)
   ) ;techParams
) ;controls
;********************************
; LAYER DEFINITION
;********************************
layerDefinitions(
 techPurposes(
 ;( PurposeName               Purpose#   Abbreviation )
 ;( -----------               --------   ------------ )
 ;User-Defined Purposes:
  ( drc                         1        drc          )
  ( lvs                         2        lvs          )
  ( block_dummy                 3        bdm          )
 ;System-Reserved Purposes:
  ( redundant                  -8        red          )
  ( gapFill                    -7        gpF          )
  ( annotation                 -6        ann          )
  ( OPCAntiSerif               -5        opcA         )
  ( OPCSerif                   -4        opcS         )
  ( slot                       -3        slt          )
  ( fill                       -2        fil          )
  ( drawing                    -1        drw          )
  ( fatal                     223        ftl          )
  ( critical                  224        crt          )
  ( soCritical                225        soC          )
  ( soError                   226        soE          )
  ( ackWarn                   227        ack          )
  ( info                      228        info         )
  ( track                     229        trk          )
  ( blockage                  230        blk          )
  ( grid                      231        grd          )
  ( warning                   234        wng          )
  ( tool1                     235        tl1          )
  ( tool0                     236        tl0          )
  ( label                     237        lbl          )
  ( flight                    238        flt          )
  ( error                     239        err          )
  ( annotate                  240        ant          )
  ( drawing1                  241        dr1          )
  ( drawing2                  242        dr2          )
  ( drawing3                  243        dr3          )
  ( drawing4                  244        dr4          )
  ( drawing5                  245        dr5          )
  ( drawing6                  246        dr6          )
  ( drawing7                  247        dr7          )
  ( drawing8                  248        dr8          )
  ( drawing9                  249        dr9          )
  ( boundary                  250        bnd          )
  ( pin                       251        pin          )
  ( net                       253        net          )
  ( cell                      254        cel          )
  ( all                       255        all          )
 ) ;techPurposes
 techLayers(
 ;( LayerName                 Layer#     Abbreviation )
 ;( ---------                 ------     ------------ )
 ;User-Defined Layers:
  ( N_Well                      1        NW           )
  ( Deep_N_Well                 2        DNW          )
  ( P_Well                      3        PW           )
  ( Active                      4        AC           )
  ( ThickActive                 5        TA           )
  ( N_Implant                   6        NI           )
  ( P_Implant                   7        PI           )
  ( Poly                        8        P1           )
  ( SilicideBlock               9        SB           )
  ( Poly2                      10        P2           )
  ( Contact                    11        CO           )
  ( Metal1                     12        M1           )
  ( Via1                       13        V1           )
  ( Metal2                     14        M2           )
  ( Via2                       15        V2           )
  ( Metal3                     16        M3           )
  ( Via3                       17        V3           )
  ( Metal4                     19        M4           )
  ( TopCapacitorPlate          18        TCP          )
  ( Passivation                20        Pass         )
  ( Resistor_ID                21        RID          )
  ( ResistorImplant            22        RI           )
  ( Diode_ID                   23        DID          )
  ( LPNP_ID                    24        LPID         )
  ( PNP_Emitter_ID             25        PEID         )
  ( NotExists                  29        NE           )
  ( Ruler                      30        Ruler        )
  ( Device_Label               31        DL           )
  ( Label                      32        Lab          )
  ( Label_Filled               33        LabF         )
  ( Label_Transparent          34        LabT         )
  ( Routing_Area               35        RtA                                                          	                 	           	            	   	 35	         	  RtA  	     	 		)
;System-Reserved Layers:
  ( Unrouted                  200        Unroute      )
  ( Row                       201        Row          )
  ( Group                     202        Group        )
  ( Cannotoccupy              203        Cannoto      )
  ( Canplace                  204        Canplac      )
  ( hardFence                 205        hardFen      )
  ( softFence                 206        softFen      )
  ( y0                        207        y0           )
  ( y1                        208        y1           )
  ( y2                        209        y2           )
  ( y3                        210        y3           )
  ( y4                        211        y4           )
  ( y5                        212        y5           )
  ( y6                        213        y6           )
  ( y7                        214        y7           )
  ( y8                        215        y8           )
  ( y9                        216        y9           )
  ( designFlow                217        designF      )
  ( stretch                   218        stretch      )
  ( edgeLayer                 219        edgeLay      )
  ( changedLayer              220        changed      )
  ( unset                     221        unset        )
  ( unknown                   222        unknown      )
  ( spike                     223        spike        )
  ( hiz                       224        hiz          )
  ( resist                    225        resist       )
  ( drive                     226        drive        )
  ( supply                    227        supply       )
  ( wire                      228        wire         )
  ( pin                       229        pin          )
  ( text                      230        text         )
  ( device                    231        device       )
  ( border                    232        border       )
  ( snap                      233        snap         )
  ( align                     234        align        )
  ( prBoundary                235        prBound      )
  ( instance                  236        instanc      )
  ( annotate                  237        annotat      )
  ( marker                    238        marker       )
  ( select                    239        select       )
  ( grid                      251        grid         )
  ( axis                      252        axis         )
  ( hilite                    253        hilite       )
  ( background                254        backgro      )
 ) ;techLayers
techLayerPurposePriorities(
;layers are ordered from lowest to highest priority
;( LayerName                 Purpose     )
;( ---------                 -------     )
 ( N_Well                    drawing     )
 ( Deep_N_Well               drawing     )
 ( P_Well                    drawing     )
 ( Active                    drawing     )
 ( Active                    fill        )
 ( Active                    block_dummy )
 ( ThickActive               drawing     )
 ( N_Implant                 drawing     )
 ( P_Implant                 drawing     )
 ( SilicideBlock             drawing     )
 ( Poly                      drawing     )
 ( Poly                      label       )
 ( Poly                      pin         )
 ( Poly                      fill        )
 ( Poly                      block_dummy )
 ( Poly                      blockage    )
 ( Poly2                     drawing     )
 ( Poly2                     label       )
 ( Poly2                     pin         )
 ( Poly2                     fill        )
 ( Poly2                     block_dummy )
 ( Poly2                     blockage    )
 ( ResistorImplant           drawing     )
 ( Metal1                    drawing     )
 ( Metal1                    label       )
 ( Metal1                    pin         )
 ( Metal1                    slot        )
 ( Metal1                    fill        )
 ( Metal1                    block_dummy )
 ( Metal1                    blockage    )
 ( Contact                   drawing     )
 ( Via1                      drawing     )
 ( Metal2                    drawing     )
 ( Metal2                    label       )
 ( Metal2                    pin         )
 ( Metal2                    slot        )
 ( Metal2                    fill        )
 ( Metal2                    block_dummy )
 ( Metal2                    blockage    )
 ( Via2                      drawing     )
 ( Metal3                    drawing     )
 ( Metal3                    label       )
 ( Metal3                    pin         )
 ( Metal3                    slot        )
 ( Metal3                    fill        )
 ( Metal3                    block_dummy )
 ( Metal3                    blockage    )
 ( Via3                      drawing     )
 ( Metal4                    drawing     )
 ( Metal4                    label       )
 ( Metal4                    pin         )
 ( Metal4                    slot        )
 ( Metal4                    fill        )
 ( Metal4                    block_dummy )
 ( Metal4                    blockage    )
 ( TopCapacitorPlate         drawing     )
 ( TopCapacitorPlate         fill        )
 ( TopCapacitorPlate         block_dummy )
 ( Passivation               drawing     )
 ( Resistor_ID               drawing     )
 ( Diode_ID                  drawing     )
 ( LPNP_ID                   drawing     )
 ( PNP_Emitter_ID            drawing     )
 ( NotExists                 drc         )
 ( Ruler                     drawing     )
 ( Device_Label              drawing     )
 ( Label                     drawing     )
 ( Label-Filled              drawing     )
 ( Label-Transparent         drawing     )
 ( annotate                  drawing     )
 ( annotate                  drawing1    )
 ( annotate                  drawing2    )
 ( annotate                  drawing3    )
 ( annotate                  drawing4    )
 ( annotate                  drawing5    )
 ( annotate                  drawing6    )
 ( annotate                  drawing7    )
 ( annotate                  drawing8    )
 ( annotate                  drawing9    )
 ( instance                  drawing     )
 ( instance                  label       )
 ( prBoundary                drawing     )
 ( prBoundary                boundary    )
 ( prBoundary                label       )
 ( Row                       drawing     )
 ( Row                       label       )
 ( align                     drawing     )
 ( hardFence                 drawing     )
 ( softFence                 drawing     )
 ( Group                     drawing     )
 ( Group                     label       )
 ( Cannotoccupy              drawing     )
 ( Cannotoccupy              boundary    )
 ( Canplace                  drawing     )
 ( text                      drawing     )
 ( text                      drawing1    )
 ( text                      drawing2    )
 ( border                    drawing     )
 ( device                    drawing     )
 ( device                    drawing2    )
 ( wire                      drawing     )
 ( wire                      label       )
 ( wire                      flight      )
 ( device                    annotate    )
 ( device                    label       )
 ( pin                       label       )
 ( pin                       drawing     )
 ( pin                       annotate    )
 ( axis                      drawing     )
 ( device                    drawing1    )
 ( edgeLayer                 drawing     )
 ( edgeLayer                 pin         )
 ( snap                      drawing     )
 ( stretch                   drawing     )
 ( y0                        drawing     )
 ( y1                        drawing     )
 ( y2                        drawing     )
 ( y3                        drawing     )
 ( y4                        drawing     )
 ( y5                        drawing     )
 ( y6                        drawing     )
 ( y7                        drawing     )
 ( y8                        drawing     )
 ( y9                        drawing     )
 ( hilite                    drawing     )
 ( hilite                    drawing1    )
 ( hilite                    drawing2    )
 ( hilite                    drawing3    )
 ( hilite                    drawing4    )
 ( hilite                    drawing5    )
 ( hilite                    drawing6    )
 ( hilite                    drawing7    )
 ( hilite                    drawing8    )
 ( hilite                    drawing9    )
 ( select                    drawing     )
 ( drive                     drawing     )
 ( hiz                       drawing     )
 ( resist                    drawing     )
 ( spike                     drawing     )
 ( supply                    drawing     )
 ( unknown                   drawing     )
 ( unset                     drawing     )
 ( designFlow                drawing     )
 ( designFlow                drawing1    )
 ( designFlow                drawing2    )
 ( designFlow                drawing3    )
 ( designFlow                drawing4    )
 ( designFlow                drawing5    )
 ( designFlow                drawing6    )
 ( designFlow                drawing7    )
 ( designFlow                drawing8    )
 ( designFlow                drawing9    )
 ( Unrouted                  drawing     )
 ( Unrouted                  drawing1    )
 ( Unrouted                  drawing2    )
 ( Unrouted                  drawing3    )
 ( Unrouted                  drawing4    )
 ( Unrouted                  drawing5    )
 ( Unrouted                  drawing6    )
 ( Unrouted                  drawing7    )
 ( Unrouted                  drawing8    )
 ( Unrouted                  drawing9    )
 ( Row                       boundary    )
 ( Unrouted                  track       )
 ( marker                    annotate    )
 ( marker                    info        )
 ( marker                    ackWarn     )
 ( marker                    soError     )
 ( marker                    soCritical  )
 ( marker                    critical    )
 ( marker                    fatal       )
 ( Group                     boundary    )
 ( y0                        flight      )
 ( y1                        flight      )
 ( y2                        flight      )
 ( y3                        flight      )
 ( y4                        flight      )
 ( y5                        flight      )
 ( y6                        flight      )
 ( y7                        flight      )
 ( y8                        flight      )
 ( y9                        flight      )
 ( border                    boundary    )
 ( snap                      grid        )
 ( changedLayer              tool0       )
 ( changedLayer              tool1       )
 ( marker                    warning     )
 ( marker                    error       )
 ( background                drawing     )
 ( grid                      drawing     )
 ( grid                      drawing1    )
 ( snap                      boundary    )
) ;techLayerPurposePriorities
techDisplays(
;(LayerName        	Purpose    	Packet      	Vis	Sel	Con2ChgLy	DrgEnbl	Valid	)
;(---------        	-------    	------      	---	---	---------	-------	-----	)
( background       	drawing    	Ruler       	t  	nil	t        	nil    	t    	)
( grid             	drawing    	Grid        	t  	nil	t        	nil    	t    	)
( N_Well           	drawing    	NWell       	t  	t  	t        	t      	t    	)
( Deep_N_Well      	drawing    	DeepNWell   	t  	t  	t        	t      	t    	)
( P_Well           	drawing    	PWell       	t  	t  	t        	t      	t    	)
( Active           	drawing    	Active      	t  	t  	t        	t      	t    	)
( Active           	fill       	Active        	t  	t  	t        	t      	t    	)
( Active           	block_dummy	Active        	t  	t  	t        	t      	t    	)
( ThickActive      	drawing    	HVActive    	t  	t  	t        	t      	t    	)
( N_Implant        	drawing    	NImplant    	t  	t  	t        	t      	t    	)
( P_Implant        	drawing    	PImplant    	t  	t  	t        	t      	t    	)
( SilicideBlock    	drawing    	NonSilicide 	t  	t  	t        	t      	t    	)
( Poly             	drawing    	Poly        	t  	t  	t        	t      	t    	)
( Poly             	label      	Poly        	t  	t  	t        	t      	t    	)
( Poly             	pin        	Poly        	t  	t  	t        	t      	t    	)
( Poly             	fill       	Poly        	t  	t  	t        	t      	t    	)
( Poly             	block_dummy	Poly        	t  	t  	t        	t      	t    	)
( Poly             	blockage   	Poly        	t  	t  	t        	t      	t    	)
( Poly2            	drawing    	Poly2       	t  	t  	t        	t      	t    	)
( Poly2            	label      	Poly2       	t  	t  	t        	t      	t    	)
( Poly2            	pin        	Poly2       	t  	t  	t        	t      	t    	)
( Poly2            	fill       	Poly2       	t  	t  	t        	t      	t    	)
( Poly2            	block_dummy	Poly2       	t  	t  	t        	t      	t    	)
( Poly2            	blockage   	Poly2       	t  	t  	t        	t      	t    	)
( ResistorImplant  	drawing    	HighResistor	t  	t  	t        	t      	t    	)
( Contact          	drawing    	Contact     	t  	t  	t        	t      	t    	)
( Metal1           	drawing    	Metal1      	t  	t  	t        	t      	t    	)
( Metal1           	label      	Metal1      	t  	t  	t        	t      	t    	)
( Metal1           	pin        	Metal1      	t  	t  	t        	t      	t    	)
( Metal1           	slot       	Metal1      	t  	t  	t        	t      	t    	)
( Metal1           	fill       	Metal1      	t  	t  	t        	t      	t    	)
( Metal1           	block_dummy	Metal1      	t  	t  	t        	t      	t    	)
( Metal1           	blockage   	Metal1      	t  	t  	t        	t      	t    	)
( Via1             	drawing    	Via1        	t  	t  	t        	t      	t    	)
( Metal2           	drawing    	Metal2      	t  	t  	t        	t      	t    	)
( Metal2           	label      	Metal2      	t  	t  	t        	t      	t    	)
( Metal2           	pin        	Metal2      	t  	t  	t        	t      	t    	)
( Metal2           	slot       	Metal2      	t  	t  	t        	t      	t    	)
( Metal2           	fill       	Metal2      	t  	t  	t        	t      	t    	)
( Metal2           	block_dummy	Metal2      	t  	t  	t        	t      	t    	)
( Metal2           	blockage   	Metal2      	t  	t  	t        	t      	t    	)
( Via2             	drawing    	Via2        	t  	t  	t        	t      	t    	)
( Metal3           	drawing    	Metal3      	t  	t  	t        	t      	t    	)
( Metal3           	label      	Metal3      	t  	t  	t        	t      	t    	)
( Metal3           	pin        	Metal3      	t  	t  	t        	t      	t    	)
( Metal3           	slot       	Metal3      	t  	t  	t        	t      	t    	)
( Metal3           	fill       	Metal3      	t  	t  	t        	t      	t    	)
( Metal3           	block_dummy	Metal3      	t  	t  	t        	t      	t    	)
( Metal3           	blockage   	Metal3      	t  	t  	t        	t      	t    	)
( Via3             	drawing    	Via3        	t  	t  	t        	t      	t    	)
( Metal4           	drawing    	Metal4      	t  	t  	t        	t      	t    	)
( Metal4           	label      	Metal4      	t  	t  	t        	t      	t    	)
( Metal4           	pin        	Metal4      	t  	t  	t        	t      	t    	)
( Metal4           	slot       	Metal4      	t  	t  	t        	t      	t    	)
( Metal4           	fill       	Metal4      	t  	t  	t        	t      	t    	)
( Metal4           	block_dummy	Metal4      	t  	t  	t        	t      	t    	)
( Metal4           	blockage   	Metal4      	t  	t  	t        	t      	t    	)
( TopCapacitorPlate	drawing    	Capacitor   	t  	t  	t        	t      	t    	)
( TopCapacitorPlate	fill       	Capacitor   	t  	t  	t        	t      	t    	)
( TopCapacitorPlate	block_dummy	Capacitor   	t  	t  	t        	t      	t    	)
( Passivation      	drawing    	Pass        	t  	t  	t        	t      	t    	)
( Resistor_ID      	drawing    	Resistor    	t  	t  	t        	t      	t    	)
( Diode_ID         	drawing    	Diode       	t  	t  	t        	t      	t    	)
( LPNP_ID          	drawing    	PNP         	t  	t  	t        	t      	t    	)
( PNP_Emitter_ID   	drawing    	PNPEMitter  	t  	t  	t        	t      	t    	)
( prBoundary        	boundary   	Subcircuit  	t  	t  	t        	t      	t    	)
( Ruler            	drawing    	Ruler       	t  	t  	t        	t      	t    	)
( Device_Label      	drawing    	BlackOutline	t  	t  	t        	t      	t    	)
( Label            	drawing    	BlackOutline	t  	t  	t        	t      	t    	)
( Label-Filled     	drawing    	FilledLabel 	t  	t  	t        	t      	t    	)
( Label-Transparent	drawing    	BlackOutline	t  	t  	t        	t      	t    	)
) ;techDisplays
techLayerProperties(
;( PropName               Layer1 [ Layer2 ]            PropValue    )
 ( perimeterCap           Poly                         4.900000e-11 )
 ( perimeterCap           Metal1                       4.260000e-11 )
 ( routingGrid            Metal1                       0.050000     )
 ( routingGrid            Via1                         0.050000     )
 ( perimeterCap           Metal2                       3.770000e-11 )
 ( routingGrid            Metal2                       0.050000     )
 ( routingGrid            Via2                         0.050000     )
 ( perimeterCap           Metal3                       3.270000e-11 )
 ( routingGrid            Metal3                       0.050000     )
 ( routingGrid            Via3                         0.050000     )
 ( perimeterCap           Metal4                       2.830000e-11 )
 ( routingGrid            Metal4                       0.050000     )
)
) ;layerDefinitions
;********************************
; LAYER RULES
;********************************
layerRules(
 streamLayers(
;(	layer               	        			StreamNum   	dataType	translate	)
;(	-----               	        			------------	--------	---------	)
( ("N_Well" "drawing")             		1 					0 			nil	)
( ("Deep_N_Well" "drawing")          	2 					0 			nil	)
( ("P_Well" "drawing")               	3 					0 			nil	)
( ("Active" "drawing")               	4 					0 			nil	)
( ("Active" "fill")                  	4 					10			nil	)
( ("Active" "block_dummy")           	4 					20			nil	)
( ("ThickActive" "drawing")          	5 					0 			nil	)
( ("N_Implant" "drawing")            	6 					0 			nil	)
( ("P_Implant" "drawing")            	7 					0 			nil	)
( ("Poly" "drawing")                 	8 					0 			nil	)
( ("Poly" "label")                   	8 					1 			nil	)
( ("Poly" "pin")                     	8 					5 			nil	)
( ("Poly" "fill")                    	8 					10			nil	)
( ("Poly" "block_dummy")             	8 					20			nil	)
( ("Poly" "blockage")                	8 					30			nil	)
( ("SilicideBlock" "drawing")        	9 					0 			nil	)
( ("Poly2" "drawing")                	10					0 			nil	)
( ("Poly2" "label")                  	10					1 			nil	)
( ("Poly2" "pin")                    	10					5 			nil	)
( ("Poly2" "fill")                   	10					10			nil	)
( ("Poly2" "block_dummy")            	10					20			nil	)
( ("Poly2" "blockage")               	10					30			nil	)
( ("ResistorImplant" "drawing")      	22					0 			nil	)
( ("Contact" "drawing")              	11					0 			nil	)
( ("Metal1" "drawing")               	12					0 			nil	)
( ("Metal1" "label")                 	12					1 			nil	)
( ("Metal1" "pin")                   	12					5 			nil	)
( ("Metal1" "slot")                  	12					7 			nil	)
( ("Metal1" "fill")                  	12					10			nil	)
( ("Metal1" "block_dummy")           	12					20			nil	)
( ("Metal1" "blockage")              	12					30			nil	)
( ("Via1" "drawing")                 	13					0 			nil	)
( ("Metal2" "drawing")               	14					0 			nil	)
( ("Metal2" "label")                 	14					1 			nil	)
( ("Metal2" "pin")                   	14					5 			nil	)
( ("Metal2" "slot")                  	14					7 			nil	)
( ("Metal2" "fill")                  	14					10			nil	)
( ("Metal2" "block_dummy")           	14					20			nil	)
( ("Metal2" "blockage")              	14					30			nil	)
( ("Via2" "drawing")                 	15					0 			nil	)
( ("Metal3" "drawing")               	16					0 			nil	)
( ("Metal3" "label")                 	16					1 			nil	)
( ("Metal3" "pin")                   	16					5 			nil	)
( ("Metal3" "slot")                  	16					7 			nil	)
( ("Metal3" "fill")                  	16					10			nil	)
( ("Metal3" "block_dummy")           	16					20			nil	)
( ("Metal3" "blockage")              	16					30			nil	)
( ("Via3" "drawing")                 	17					0 			nil	)
( ("Metal4" "drawing")               	19					0 			nil	)
( ("Metal4" "label")                 	19					1 			nil	)
( ("Metal4" "pin")                   	19					5 			nil	)
( ("Metal4" "slot")                  	19					7 			nil	)
( ("Metal4" "fill")                  	19					10			nil	)
( ("Metal4" "block_dummy")           	19					20			nil	)
( ("Metal4" "blockage")              	19					30			nil	)
( ("TopCapacitorPlate" "drawing")    	18					0 			nil	)
( ("TopCapacitorPlate" "fill")       	18					10			nil	)
( ("TopCapacitorPlate" "block_dummy")	18					20			nil	)
( ("Passivation" "drawing")          	20					0 			nil	)
( ("Resistor_ID" "drawing")          	21					0 			nil	)
( ("Diode_ID" "drawing")             	23					0 			nil	)
( ("LPNP_ID" "drawing")              	24					0 			nil	)
( ("PNP_Emitter_ID" "drawing")       	25					0 			nil	)
( ("prBoundary" "boundary")          	26					0 			nil	)
) ;streamLayers
) ;layerRules
;********************************
; PHYSICAL RULES
;********************************
physicalRules(
 mfgGridResolution( (0.0500)) ;mfgGridResolution
 orderedSpacingRules(
  ;( rule             layer1          layer2            value )
  ;( ----             ------          ------            ----- )
   ( MinEnclosure     "Metal1"        "Contact"         0.100 )
   ( MinEnclosure     "Metal1"        "Via1"            0.150 )
   ( MinEnclosure     "Metal2"        "Via1"            0.150 )
   ( MinEnclosure     "Metal2"        "Via2"            0.150 )
   ( MinEnclosure     "Metal3"        "Via2"            0.150 )
   ( MinEnclosure     "Metal3"        "Via3"            0.150 )
   ( MinEnclosure     "Metal4"        "Passivation"     6.000 )
   ( MinEnclosure     "Metal4"        "Via3"            0.150 )
   ( MinEnclosure     "N_Implant"     "Active"          0.250 )
   ( MinEnclosure     "P_Implant"     "Active"          0.250 )
   ( MinEnclosure     "Poly"          "Contact"         0.150 )
   ( MinEnclosure     "ThickActive"   "Active"          0.500 )
   ( minExtension     "Active"        "SilicideBlock"   0.350 )
   ( minExtension     "Deep_N_Well"   "N_Well"          1.500 )
   ( minExtension     "Poly"          "Active"          0.300 )
   ( minExtension     "Poly"          "SilicideBlock"   0.350 )
   ( minExtension     "SilicideBlock" "Active"          0.250 )
   ( minOverlap       "N_Well"        "Deep_N_Well"     1.750 )
  ) ;orderedSpacingRules
 spacingRules(
  ;( rule          layer1           layer2         value )
  ;( ----          ------           ------         ----- )
   ( minWidth      "N_Well"                        1.450 )
   ( minWidth      "Deep_N_Well"                   4.000 )
   ( minWidth      "P_Well"                        1.450 )
   ( minWidth      "Active"                        0.350 )
   ( minWidth      "ThickActive"                   0.500 )
   ( minWidth      "N_Implant"                     0.500 )
   ( minWidth      "P_Implant"                     0.500 )
   ( minWidth      "SilicideBlock"                 0.500 )
   ( minWidth      "Poly"                          0.250 )
   ( minWidth      "Contact"                       0.250 )
   ( minWidth      "Metal1"                        0.350 )
   ( minWidth      "Via1"                          0.350 )
   ( minWidth      "Metal2"                        0.350 )
   ( minWidth      "Via2"                          0.350 )
   ( minWidth      "Metal3"                        0.350 )
   ( minWidth      "Via3"                          0.350 )
   ( minWidth      "Metal4"                        0.350 )
   ( minSpacing    "N_Well"                        0.750 )
   ( minSpacing    "Deep_N_Well"                   6.500 )
   ( minSpacing    "P_Well"                        0.750 )
   ( minSpacing    "Active"                        0.350 )
   ( minSpacing    "ThickActive"                   0.500 )
   ( minSpacing    "N_Implant"                     0.500 )
   ( minSpacing    "P_Implant"                     0.500 )
   ( minSpacing    "Poly"                          0.350 )
   ( minSpacing    "SilicideBlock"                 0.500 )
   ( minSpacing    "Contact"                       0.500 )
   ( minSpacing    "Metal1"                        0.350 )
   ( minSpacing    "Via1"                          0.350 )
   ( minSpacing    "Metal2"                        0.500 )
   ( minSpacing    "Via2"                          0.350 )
   ( minSpacing    "Metal3"                        0.500 )
   ( minSpacing    "Via3"                          0.350 )
   ( minSpacing    "Metal4"                        0.500 )
   ( minSpacing    "Active"         "Poly"         0.200 )
   ( minSpacing    "Active"         "ThickActive"  0.500 )
   ( minSpacing    "Deep_N_Well"    "N_Well"       4.750 )
   ( minSpacing    "SilicideBlock"  "Active"       0.250 )
   ( minSpacing    "SilicideBlock"  "Poly"         0.250 )
 ) ;spacingRules
) ;physicalRules
;********************************
; DEVICES
;********************************
devices(
 symContactDevice(
 ; (name viaLayer viaPurpose layer1 purpose1 layer2 purpose2
 ;  w l (row column xPitch yPitch xBias yBias) encByLayer1 encByLayer2 legalRegion)

   (M1_POLY Contact drawing Poly drawing Metal1 drawing
   0.25 0.25 (1 1 0.75 0.75 center center) 0.15 0.15 _NA_)

   (M2_M1 Via1 drawing Metal1 drawing Metal2 drawing
   0.35 0.35 (1 1 0.75 0.75 center center) 0.15 0.15 _NA_)

   (M1_Act Contact drawing Active drawing Metal1 drawing
   0.25 0.25 (1 1 0.75 0.75 center center) 0.15 0.15 _NA_)

   (M1_N Contact drawing Active drawing (N_Implant drawing 0.4) Metal1 drawing
   0.25 0.25 (1 1 0.75 0.75 center center) 0.15 0.15 (outside N_Well drawing))

   (M1_P Contact drawing Active drawing (P_Implant drawing 0.4) Metal1 drawing
   0.25 0.25 (1 1 0.75 0.75 center center) 0.15 0.15 (inside N_Well drawing))

   (NTAP Contact drawing Active drawing (N_Implant drawing 0.4) Metal1 drawing (N_Well drawing 0.5)
   0.25 0.25 (1 1 0.75 0.75 center center) 0.15 0.15 (inside N_Well drawing))

   (PTAP Contact drawing Active drawing (P_Implant drawing 0.4) Metal1 drawing
   0.25 0.25 (1 1 0.75 0.75 center center) 0.15 0.15 (outside N_Well drawing))

   (M3_M2 Via2 drawing Metal2 drawing Metal3 drawing
   0.35 0.35 (1 1 0.75 0.75 center center) 0.15 0.15 _NA_)

   (M4_M3 Via3 drawing Metal3 drawing Metal4 drawing
   0.35 0.35 (1 1 0.75 0.75 center center) 0.15 0.15 _NA_)
 )
)
