********************************************************************************
* SPICE netlist generated by HiPer Verify's NetList Extractor
*
* Extract Date/Time:	Thu Feb 14 14:54:15 2013
* L-Edit Version:		L-Edit Win64 16.00.20130213.07:27:00
*
* Rule Set Name:		
* TDB File Name:		S:\TannerTools\main\TannerToolsShippingFiles\Process\Generic_250nm\Generic_250nm_AnalogLib\OA\lib.defs
* Command File:		S:\TannerTools\main\TannerToolsShippingFiles\Process\Generic_250nm\Generic_250nm_Tech\OA\Rules\Generic_250nm_LVS.cal
* Cell Name:			R2RDAC8
* Write Flat:			NO
********************************************************************************

.LIB '..\..\..\Generic_250nm_Tech\Generic_250nm.lib' LVS

****************************************
.SUBCKT pmos25_Auto1 1 2 B D S
M1 D 1 S B PMOS25 l=2.5e-007 w=5.1e-006 ad=1.9125e-012 as=3.315e-012 pd=5.85e-006 ps=1.15e-005  $ (0 0 0.25 5.1)
M2 2 1 D B PMOS25 l=2.5e-007 w=5.1e-006 ad=1.9125e-012 as=1.9125e-012 pd=5.85e-006 ps=5.85e-006  $ (1 0 1.25 5.1)
* Device count
* M(PMOS25)		2
* Number of devices:	2
* Number of nodes:	5
.ENDS

****************************************
.SUBCKT nmos25_Auto1 1 2 3 B S
M1 1 2 3 B NMOS25 l=2.5e-007 w=1.9e-006 ad=7.125e-013 as=1.235e-012 pd=2.65e-006 ps=5.1e-006  $ (0 0 0.25 1.9)
M2 S 2 1 B NMOS25 l=2.5e-007 w=1.9e-006 ad=7.125e-013 as=7.125e-013 pd=2.65e-006 ps=2.65e-006  $ (1 0 1.25 1.9)
* Device count
* M(NMOS25)		2
* Number of devices:	2
* Number of nodes:	5
.ENDS

****************************************
.SUBCKT HD_rhp_Auto1 RM RP
X1 RM RP rhp l=1e-005 w=2e-006  $ (0 0 2 10)
* Device count
* X(rhp)		1
* Number of devices:	1
* Number of nodes:	2
.ENDS

****************************************
.SUBCKT HD_rhp_Auto1[6x1]x[2500x12150] 1 2 3 4 5 6 7 8 9 10 RM RP
X2 RM RP HD_rhp_Auto1  $ (-0.25 -1.075 2.25 11.075) $T=0 0 0 0 1
X3 1 2 HD_rhp_Auto1  $ (2.25 -1.075 4.75 11.075) $T=2.5 0 0 0 1
X4 3 4 HD_rhp_Auto1  $ (4.75 -1.075 7.25 11.075) $T=5 0 0 0 1
X5 5 6 HD_rhp_Auto1  $ (7.25 -1.075 9.75 11.075) $T=7.5 0 0 0 1
X6 7 8 HD_rhp_Auto1  $ (9.75 -1.075 12.25 11.075) $T=10 0 0 0 1
X7 9 10 HD_rhp_Auto1  $ (12.25 -1.075 14.75 11.075) $T=12.5 0 0 0 1
* Device count
* Number of devices:	0
* Number of nodes:	12
.ENDS

****************************************
.SUBCKT DAC_BIT Bit_In Vin Vout VrefM VrefP
M1 VrefM bb b VrefM NMOS25 l=2.5e-007 w=1.9e-006 ad=7.125e-013 as=7.125e-013 pd=2.65e-006 ps=2.65e-006  $ (20.725 32.775 22.625 33.025)
M2 bb Bit_In VrefM VrefM NMOS25 l=2.5e-007 w=1.9e-006 ad=1.235e-012 as=7.125e-013 pd=5.1e-006 ps=2.65e-006  $ (20.725 33.775 22.625 34.025)
M3 VrefP bb b VrefP PMOS25 l=2.5e-007 w=5.1e-006 ad=1.9125e-012 as=1.9125e-012 pd=5.85e-006 ps=5.85e-006  $ (12.775 32.775 17.875 33.025)
M4 bb Bit_In VrefP VrefP PMOS25 l=2.5e-007 w=5.1e-006 ad=3.315e-012 as=1.9125e-012 pd=1.15e-005 ps=5.85e-006  $ (12.775 33.775 17.875 34.025)
XU5 bb b VrefP VrefP b pmos25_Auto1  $ (10.975 28.325 18.625 34.425) $T=17.875 30.775 0 270 1
XU3 VrefM bb b VrefM b nmos25_Auto1  $ (20.425 28.825 23.925 33.925) $T=22.625 30.775 0 270 1
XU10 1 Vin RM 2 3 2 1 Vout 3 Vout RM b HD_rhp_Auto1[6x1]x[2500x12150]  $ (9.95 12.725 24.95 24.875) $T=10.2 13.8 0 0 1
* Device count
* M(NMOS25)		2
* M(PMOS25)		2
* Number of devices:	4
* Number of nodes:	11
.ENDS

****************************************
.SUBCKT DAC_BIT[8x1]x[15250x28700] 1 3 5 7 9 11 13 14 Bit_In Vin VrefM VrefP
X2 Bit_In Vin Vout VrefM VrefP DAC_BIT  $ (9.825 10.025 25.075 38.725) $T=0 0 0 0 1
X3 1 Vout 2 VrefM VrefP DAC_BIT  $ (25.075 10.025 40.325 38.725) $T=15.25 0 0 0 1
X4 3 2 4 VrefM VrefP DAC_BIT  $ (40.325 10.025 55.575 38.725) $T=30.5 0 0 0 1
X5 5 4 6 VrefM VrefP DAC_BIT  $ (55.575 10.025 70.825 38.725) $T=45.75 0 0 0 1
X6 7 6 8 VrefM VrefP DAC_BIT  $ (70.825 10.025 86.075 38.725) $T=61 0 0 0 1
X7 9 8 10 VrefM VrefP DAC_BIT  $ (86.075 10.025 101.325 38.725) $T=76.25 0 0 0 1
X8 11 10 12 VrefM VrefP DAC_BIT  $ (101.325 10.025 116.575 38.725) $T=91.5 0 0 0 1
X9 13 12 14 VrefM VrefP DAC_BIT  $ (116.575 10.025 131.825 38.725) $T=106.75 0 0 0 1
* Device count
* Number of devices:	0
* Number of nodes:	19
.ENDS

****************************************
.SUBCKT DAC_IN Adjust_In Vout VrefM
XU10 1 Adjust_In VrefM VrefM VrefM VrefM 1 Vout VrefM VrefM VrefM VrefM HD_rhp_Auto1[6x1]x[2500x12150]  $ (9.95 12.725 24.95 24.875) $T=10.2 13.8 0 0 1
* Device count
* Number of devices:	0
* Number of nodes:	4
.ENDS

****************************************

XU11 B<1> B<2> B<3> B<4> B<5> B<6> B<7> Vout B<0> Vin VrefM VrefP DAC_BIT[8x1]x[15250x28700]  $ (0 0 122 28.7) $T=-9.825 -10.025 0 0 1
XU13 Adj Vin VrefM DAC_IN  $ (-15.25 0 0 28.7) $T=-25.075 -10.025 0 0 1
* Top level device count
* Number of devices:	0
* Number of nodes:	13


* Cumulative top level and subcircuit device count
* M(NMOS25)		4
* M(PMOS25)		4
* X(rhp)		1
* Number of devices:	9
* Number of nodes:	71
