********************************************************************************
* SPICE netlist generated by HiPer Verify's NetList Extractor
*
* Extract Date/Time:	Thu Feb 14 11:22:45 2013
* L-Edit Version:		L-Edit Win64 16.00.20130213.07:27:00
*
* Rule Set Name:		
* TDB File Name:		S:\TannerTools\main\TannerToolsShippingFiles\Process\Generic_250nm\Generic_250nm_AnalogLib\OA\lib.defs
* Command File:		S:\TannerTools\main\TannerToolsShippingFiles\Process\Generic_250nm\Generic_250nm_Tech\OA\Rules\Generic_250nm_LVS.cal
* Cell Name:			DAC_IN
* Write Flat:			NO
********************************************************************************

.LIB '..\..\..\Generic_250nm_Tech\Generic_250nm.lib' LVS

****************************************
.SUBCKT HD_rhp_Auto1 RM RP
X1 RM RP rhp l=1e-005 w=2e-006  $ (0 0 2 10)
* Device count
* X(rhp)		1
* Number of devices:	1
* Number of nodes:	2
.ENDS

****************************************
.SUBCKT HD_rhp_Auto1[6x1]x[2500x12150] 1 2 3 4 5 6 7 8 9 10 RM RP
X2 RM RP HD_rhp_Auto1  $ (-0.25 -1.075 2.25 11.075) $T=0 0 0 0 1
X3 1 2 HD_rhp_Auto1  $ (2.25 -1.075 4.75 11.075) $T=2.5 0 0 0 1
X4 3 4 HD_rhp_Auto1  $ (4.75 -1.075 7.25 11.075) $T=5 0 0 0 1
X5 5 6 HD_rhp_Auto1  $ (7.25 -1.075 9.75 11.075) $T=7.5 0 0 0 1
X6 7 8 HD_rhp_Auto1  $ (9.75 -1.075 12.25 11.075) $T=10 0 0 0 1
X7 9 10 HD_rhp_Auto1  $ (12.25 -1.075 14.75 11.075) $T=12.5 0 0 0 1
* Device count
* Number of devices:	0
* Number of nodes:	12
.ENDS

****************************************

XU10 1 Adjust_In VrefM VrefM VrefM VrefM 1 Vout VrefM VrefM VrefM VrefM HD_rhp_Auto1[6x1]x[2500x12150]  $ (9.95 12.725 24.95 24.875) $T=10.2 13.8 0 0 1
* Top level device count
* Number of devices:	0
* Number of nodes:	4


* Cumulative top level and subcircuit device count
* X(rhp)		1
* Number of devices:	1
* Number of nodes:	18
